Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false